### Create pofile
POST localhost:8080/api/v1/auth/login
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk2MTc4NzUsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk2MjE0NzUsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.-CkDWmjz8aT-gaTrWhpmvlsmhTCwuyapPSfLCq03uVcTUHRFTmfKiRr3I2VZwYBoadE5qeselA_NoW-ZcsyBiw

{
  "phone": "1234564",
  "password": "12345"
}

### Registration
POST localhost:8080/api/v1/auth/registration
Content-Type:  application/json

{ "name": "Ali",
  "surname": "Aliyev",
  "email": "testkunpro@gmail.com",
  "password": "12345"
}